# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8a818db8-a690-4478-a9ee-8e3df9ecfdae";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd:5" "ssd" "discard=async" "space_cache=v2" "subvol=root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8a818db8-a690-4478-a9ee-8e3df9ecfdae";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd:5" "ssd" "discard=async" "space_cache=v2" "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8a818db8-a690-4478-a9ee-8e3df9ecfdae";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd:5" "ssd" "discard=async" "space_cache=v2" "subvol=home" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/5632-922A";
      fsType = "vfat";
    };

   swapDevices =
    [ { device = "/dev/disk/by-uuid/ef6d1409-5ecf-413b-8408-7265f05b1bc9"; }
    ];

  fileSystems."/home/ja/00shared-drives/1TB-NVME" =
    { device = "/dev/disk/by-uuid/15d348b6-c5a4-4eb9-8d14-8f33da2ab912";
      fsType = "ext4";
    };

  fileSystems."/home/ja/00shared-drives/1TB-SSD" =
    { device = "/dev/disk/by-uuid/6a061ba4-d0be-416e-9853-7fe9862c8f63";
      fsType = "ext4";
    };

  fileSystems."/home/ja/00shared-drives/500G-NVME" =
    { device = "/dev/disk/by-uuid/797a4922-3b58-4bdd-ad7e-4ddac564d3de";
      fsType = "ext4";
    };

  fileSystems."/home/ja/00shared-drives/Data-Momentus-XT" =
    { device = "/dev/disk/by-uuid/11bc1730-7b19-48dd-8bde-05fa54308860";
      fsType = "ext4";
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
